### ISSUE TITLE
Libtorrent - help

### ISSUE THREAD

**Issue by VuzzyM** [i96751414/torrest#4]
@i96751414 
Hi, can you somehow help to implement libtorrent for this project, in this project anacrolix torrent is ​​used.  But libtorrent is much better and has no bugs.  The author tried to implement it, but something is not received, a great help would be desirable if possible, thank you very much, I hope you help

https://github.com/YouROK/TorrServer

**Comment by i96751414** [comment]
Hi. That should be discussed with the author of that project.
You may use https://github.com/i96751414/libtorrent-go to make libtorrent calls.

**Comment by VuzzyM** [comment]
@i96751414  Do you have a telegram so you can join the developer group?
Or you want a special topic on github with developer?

**Comment by Lontron** [comment]
Or you want a special topic on github with developer?
