### ISSUE TITLE
[Help] Libtorrent-go

### ISSUE THREAD

**Issue by VuzzyM** [i96751414/torrest#5]
Where is the api?  Or how can I create a function/calls for an android application? Please help
https://github.com/i96751414/libtorrent-go

**Comment by i96751414** [comment]
Hi, sorry for the late reply. Libtorrent-go is a project containing go bindings (generated by SWIG) for libtorrent (https://github.com/arvidn/libtorrent). Therefore, the api can be found on libtorrent project documentation.
